# Generated by Django 4.0 on 2021-12-27 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('number_of_teams', models.IntegerField()),
                ('current_champion', models.CharField(max_length=50, null=True)),
                ('most_championships', models.CharField(max_length=50, null=True)),
                ('most_appearances', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'League',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('championships_won', models.IntegerField()),
                ('coach', models.CharField(max_length=100)),
                ('number_of_players', models.IntegerField()),
                ('league', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='football.league')),
            ],
            options={
                'db_table': 'Team',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('position', models.CharField(max_length=30)),
                ('appearances', models.IntegerField()),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='football.team')),
            ],
            options={
                'db_table': 'Player',
            },
        ),
    ]
